### ISSUE TITLE
Keep price impact in place when updating price

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2456]
Steps to repro
1. Enter a trade like 1 ETH for DAI
2. Observe price impact is shown in the output field (e.g. -0.3%)
3. Change the input value
4. Observe price impact *disappears* until a new quote is received. This created a lot of motion and flickering.

Expected behavior:  the price impact should stay in place and be grayed out (like the output amount next to it) until a new quote is received.

**Comment by willhennessy** [comment]
yes the value of the trade remains, but the % price impact disappears until a new quote is fetched. e.g. "-0.213%"

ideally that should be grayed out just like the value, instead of disappearing

would you like to pick up this issue?

**Comment by justindomingue** [comment]
@prakashsanker probably a good first issue. We remove the price impact because it's derived from the user input, not the trade state. What that means is that when the user types in a new number, the price impact update. 

`priceimpact` is manually set to `undefined` (hidden) when the route is syncing. Note quite sure what the best solution is here. Maybe `priceImpact` could be moved inside `useDerivedSwapInfo` and calculate from the last trade.

**Comment by prakashsanker** [comment]
@willhennessy  I am on this issue and https://github.com/Uniswap/interface/issues/2519. Taking both as I am in the India time zone right now and there's a decent turnaround time for my questions.

Would you guys be open to me pinging you on discord or something to get qs answered?

**Comment by willhennessy** [comment]
fixed by #2975
