### ISSUE TITLE
Safari square dots

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2457]
In the Auto Router route visualization, the dots are rendered as squares in the Safari browser.  They should be rendered as round circles.

<img width="767" alt="Screen Shot 2021-09-13 at 3 46 22 PM" src="https://user-images.githubusercontent.com/5455577/134983033-368abc2f-885b-4aa6-954e-eb30c11c7dd8.png">

**Comment by Armakuji** [comment]
Fixed ✨

https://github.com/Uniswap/interface/pull/2474

**Comment by Armakuji** [comment]
Oh!! I found it did not work in Safari either.So I should find another solution to fix it.

**Comment by willhennessy** [comment]
Thanks! let us know when you find another solution

**Comment by Armakuji** [comment]
@willhennessy I'm done ✨. I am using Dot SVG instead of border-style CSS.
Please review the pull request . https://github.com/Uniswap/interface/pull/2474

Result.

| Browser | Result Image |
| ------------- | ------------- |
| Chrome  |  <img width="1440" alt="chrome_route" src="https://user-images.githubusercontent.com/77143416/135902159-fc0e821a-c5d8-488c-a017-1a567b3327b2.png">   |
| Safari  |   <img width="1440" alt="safari_route" src="https://user-images.githubusercontent.com/77143416/135902222-8db7deaa-b16b-4838-946a-2249db5d4dfd.png">  |

**Comment by willhennessy** [comment]
Thanks! Justin will review

**Comment by willhennessy** [comment]
great job Armakuji!! The fix has been released and I verified on my end :)
