### ISSUE TITLE
Output token cannot be selected

### ISSUE THREAD

**Issue by callil** [Uniswap/interface#2513]
Reported by Discord user: https://discord.com/channels/597638925346930701/606886929094541313/895749819744796832

![image](https://user-images.githubusercontent.com/1355319/136448005-93d2b281-0478-4865-9807-2367d8f69ba2.png)

Investigating how to repro

**Comment by justindomingue** [comment]
@ianlapham @zzmp I think it's related to the visibility change on the token selector

**Comment by willhennessy** [comment]
hi justin, what do we mean "a token address fails to resolve on the chain"?  Do we mean if there is no contract deployed at that address?

how often does this occur?

This bug pretty much breaks the swap page so feels like high severity even if it's a rare occurrence

**Comment by willhennessy** [comment]
got it, that will grow increasingly common.  How about this for a quick fix?  When the token address fails to resolve, can we reset that token field (input or output) to the default value?

For example
1. the user follows a link to swap USDC -> 0x1234
2. 0x1234 is not resolved
3. reset 0x1234 to the default state:  empty.
4. the input field is unchanged (USDC) because it was resolved
5. if the input field was not resolved, it would reset to the default state:  ETH

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/3056
