### ISSUE TITLE
ENS avatars are not supported if it is in eip155:1/erc1155 format

### ISSUE THREAD

**Issue by bigint** [Uniswap/interface#3010]
**Bug Description**

ENS avatars are not supported if it is in eip155:1/erc1155 format

**Steps to Reproduce**

1. Go to ENS record
2. Update avatar to `eip155:1/erc1155:0x495f947276749ce646f68ac8c248420045cb7b5e/26396376898576019325902668567942607247753500533935235934491478862732929794049`
3. Visit Uniswap and check the avatar

**Expected Behavior**

It should display an avatar

**Additional Context**

It's making weird opensea request

<img width="719" alt="Screenshot 2021-12-19 at 8 54 59 PM" src="https://user-images.githubusercontent.com/69431456/146680603-5247fc97-9fb0-46d2-9ef8-377ae5f31257.png">

Suggested to use ENS's metadata service https://metadata.ens.domains/mainnet/avatar/yoginth.eth

**Comment by uniyj** [comment]
I'm not super familiar with NFT EIPs, but I've had a look, and I don't think it's a question of "_ENS avatars are not supported if it is in eip155:1/erc1155 format_"…

The NFT avatar posted was "lazy minted" on OpenSea, and so I think it's not found on-chain. Hence, Uniswap UI's avatar query fails to load it.

The ENS Metadata Service seems to return the metadata and image info because it uses OpenSea's API (see [here](https://github.com/ensdomains/ens-metadata-service/blob/master/src/avatar.ts)), which is able (for obvious reasons!) to return the offchain info from its own "lazy mint".

Of course, Uniswap Team can decide to use the ENS Metadata Service API instead, as you suggested. They will need to make a decision to start relying on off-chain data from OpenSea though, which obviously reduces decentralisation. (Note: I am not familiar with TS / React / Frontend, and so I don't really know how best to implement the usage of ENS Metadata Service, even though it's just a straightforward API endpoint call to get JSON payload)

**Comment by bigint** [comment]
> The NFT avatar posted was "lazy minted" on OpenSea, and so I think it's not found on-chain. Hence, Uniswap UI's avatar query fails to load it.

@uniyj IMO it's not lazy minted, its completely minted and available on-chain

https://etherscan.io/token/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85?a=0x3a5bd1e37b099ae3386d13947b6a90d97675e5e3#inventory

We can resolve the avatar on-chain using ethers here is the example I made in Olympus https://github.com/OlympusDAO/olympus-frontend/blob/develop/src/hooks/useENS.ts#L15

**Comment by bigint** [comment]
I think its already there and it seems like a bug resolving it https://github.com/Uniswap/interface/blob/main/src/hooks/useENSAvatar.ts#L76-L80

**Comment by uniyj** [comment]
Ok, I've had another dig around, and I think there are a couple of things here that got mixed up.

I agree with you that there is likely a bug/omission that resulted in the `404` you screenshot-ed in the "additional context" you posted. I think it's missing the equivalent of the following code from [here](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts):

```
// ERC-1155 allows a generic {id} in the URL
  if (match[1] === "erc1155") {
      metadataUrl = metadataUrl.replace("{id}", tokenId.substring(2));
      linkage.push({ type: "metadata-url-expanded", content: metadataUrl });
  }
```

I don't know enough TS re: how to implement something like that in [here](https://github.com/Uniswap/interface/blob/main/src/hooks/useENSAvatar.ts), but probably it should go into the `useERC1155Uri` function, to have code to replace `{id}` with the hex-tokenId before requesting for the metadata JSON. Hopefully someone can help implement and merge that.

\<end of code related stuff\>

Less importantly, something kinda unrelated, but just my opinion on whether data is "on-chain":

> @uniyj IMO it's not lazy minted, its completely minted and available on-chain
> 
> https://etherscan.io/token/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85?a=0x3a5bd1e37b099ae3386d13947b6a90d97675e5e3#inventory

The link you posted above is for your ENS name NFT, i.e. yoginth.eth. As far as I know, there is no equivalent etherscan link for your **avatar** NFT (i.e. what I noted in comment above), because it is lazy-minted on OpenSea and currently only "exists" in OpenSea's data, not on-chain. When querying your ENS name NFT (yoginth.eth) for metadata related to avatar, it returns the [OpenSea Shared Storefront contract](https://etherscan.io/address/0x495f947276749ce646f68ac8c248420045cb7b5e) address and the token ID. However, that token ID cannot actually be found on-chain because it was lazy-minted (0 gas) and not broadcast to chain. Compare that with, for example, nick.eth's avatar metadata, which is also on the OpenSea Shared Storefront contract, but was broadcasted on chain (because there was a sale and a transfer) – you will find [this](https://etherscan.io/token/0x495f947276749ce646f68ac8c248420045cb7b5e?a=8112316025873927737505937898915153732580103913704334048512380490797008551937).

**Comment by bigint** [comment]
Ohh yes indeed @uniyj, my avatar is lazy minted on opensea, but I'd suggest uni swap to use ENS's metadata service to fetch avatars right?

https://metadata.ens.domains/mainnet/avatar/yoginth.eth/meta
https://metadata.ens.domains/mainnet/avatar/yoginth.eth

**Comment by uniyj** [comment]
Ok, despite my very limited TS skillz, I've done some quick tests, and I think I have something that works, to replace the `{id}` returned by 1155 `uri` call and get to the eventual OpenSea API address (which in turn returns the `image` link, even though it's not "on-chain"). Will submit a PR and let others check and modify.

**Comment by bigint** [comment]
Great @uniyj 👍🏻

**Comment by uniyj** [comment]
This is now merged. Please close. Thanks.
