### ISSUE TITLE
Pool page should get the min/max tick from URL params

### ISSUE THREAD

**Issue by dmihal** [Uniswap/interface#3111]
**Is your feature request related to a problem? Please describe.**
I'm one of the contributors to the project for [liquidity mining on L2s](https://gov.uniswap.org/t/temperature-check-should-uniswap-incentivize-liquidity-on-optimism-and-arbitrum/14804). We've updated the Uniswap staking contracts to add minimum-tick ranges, and we're now working to build a new user interface for staking.

Since the idea of "minimum tick ranges" adds a bit of complexity, we'd like to let a user decide their tick range in the staking UI, then click a link that will take them to the Uniswap frontend with the desired ticks pre-selected. 

**Describe the solution you'd like**
The UI currently encoded the 2 assets and fee tier, as well as an optional position ID:

```
https://app.uniswap.org/#/add/<asset0>/<asset1>/<fee>[/<positionId>]
https://app.uniswap.org/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000
```

Ideally, it should also accept some query parameters to set the ticks, as follows:

```
https://app.uniswap.org/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000?tickMin=-1000&tickMax=1000
```

**Comment by willhennessy** [comment]
Thanks for the suggestion! If I recall, @justindomingue considered this last summer. Just wdyt?

**Comment by justindomingue** [comment]
Should be possible. We do it for the swap state here: https://github.com/Uniswap/interface/blob/1efda07e7a8dd6882b9beaf3a11ad22129f09b8c/src/state/swap/hooks.tsx#L184-L270

one awkwardness is our add liquidity state stores prices at ticks rather than ticks so there may be a slight difference between the ticks defined in the url and what the page resolved to. Probably will not be an issue for most tokens
