### ISSUE TITLE
IOS wallets crash when inputting amounts 

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3133]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "recipient": null,
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "INPUT": {
    "currencyId": "0xBA11D00c5f74255f56a5E366F4F77f5A186d7f55"
  },
  "independentField": "INPUT",
  "typedValue": "2"
}
```

## Error

```
ReferenceError: Can't find variable: ResizeObserver
```

## Stacktrace

```
https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2815713
https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2815435
https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2815548
Mu@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2997168
Mu@[native code]
unstable_runWithPriority@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3016379
Ru@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2993788
wu@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2989874
wu@[native code]
https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2939142
unstable_runWithPriority@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3016379
Ki@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2939088
Wi@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2939023
https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3010339
je@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3010342
Be@https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2909385
https://app.uniswap.org/static

**Comment by willhennessy** [comment]
Hi Rachel, what wallet app are you using? I'm unable to repro on iOS chrome or iOS Coinbase Wallet

**Comment by Rachel-Eichenberger** [comment]
@willhennessy 

I got this crash in MM, though i've seen users with trustwallet and coinbase too.  Happens as soon as inputting a value.  Steps I take exactly. load site normal, switch token position ETH bottom, Select token (any seems), input amount of token
metamask up to date on store version 3.8 IOS version 12.5.5

**Comment by Rachel-Eichenberger** [comment]
I do get the same issue with my coinbase, Hmmm

**Comment by Rachel-Eichenberger** [comment]
Maybe an wallet update or maybe IOS update but not seeing this issue with mine anymore, and haven't been seeing this issue in discord

**Comment by Rds2008ca-libellule** [comment]
Kelly Desjarlais has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [Uniswap/interface] IOS wallets crash when inputting amounts (Issue #3133) <https://confidential-mail.google.com/msg/AOYjdi0DU9mkfa06tIheJinDqsjsJMA_RqEKlBuq8CxZfL1GpNz6G8rTEVFpQeCBHlHSY4p8h2Vr6Qkj3yYkKt9ntiED7wGcjp6rQI0HX36BJ4i3q0YzlyYelVNCTuZnkioElTyKjeO8uQXoXmF2pHc_tvxZXEnhnOjB18n-dmeoi0_jk0b40F7bZq-lMJLYc1Gf3Mi4-wY5vTVVRKMM6g==>

This message was sent on 13 Feb 2022 at 03:53:39 GMT-8
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AOYjdi0DU9mkfa06tIheJinDqsjsJMA_RqEKlBuq8CxZfL1GpNz6G8rTEVFpQeCBHlHSY4p8h2Vr6Qkj3yYkKt9ntiED7wGcjp6rQI0HX36BJ4i3q0YzlyYelVNCTuZnkioElTyKjeO8uQXoXmF2pHc_tvxZXEnhnOjB18n-dmeoi0_jk0b40F7bZq-lMJLYc1Gf3Mi4-wY5vTVVRKMM6g==>

Gmail confidential mode gives you more control over the messages that you send. The sender may have chosen to set an expiry time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en-GB>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]
