### ISSUE TITLE
Metamask and Coinbase popup when connecting with metamask

### ISSUE THREAD

**Issue by mcgraneder** [Uniswap/interface#3156]
**Bug Description**
Ok so I noticed something that is not unique to uniswap i tried on other dapps like DYDX and the same happens. If a user has both the metamask and coinbase extension on chrome browser and the user connects to uniswap with metamask then both popups show for metamask and uniswap requesting to connect. this only happens when ctrying to connect with metamask and doesnt happen if the user tries to connect with coinbase

**Steps to Reproduce**

1. Get both the metamask and coinbase chrome wallet extensions
2. Go to uniswap if you have any metamask accounts conected lock your wallet to logout
3. refresh the page and connect with metamask. Both popups appear
   ...

**Expected Behavior**
Ideally only the metamask popup should appear

**Additional Context**
This problem might not be so bad for uniswap but for multiple page applications especially ones with digital signature auth this could get annoying and potentially cause unexpected errors. especially if the user clicked on coinbase but wanted to connect with metamask instead you have to manually go into the coinbase wallet and disconnect which is a pain. I actuallly removed the coinbase wallet from chrome on my machine because it kept popping up using different Dapps.

I know this is not an issue with the uniswap code but i think its to do with the provider. but would there be a possible fix to this

**Comment by willhennessy** [comment]
thank you for the detailed report! really appreciate it. We've seen weird behavior in the past when both Metamask and Coinbase extension are installed. Unfortunately, the issue lies in those extensions and the way they respond to window.ethereum events. I don't think there's anything we can do in the Uniswap App except wait for extensions or browser ethereum standards to improve. Let me know if I'm wrong though!

Personally I've been dismissing the extra dialogs and it's quite annoying :)
