### ISSUE TITLE
use localstorage to store a client identifier for analytics

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/interface#3204]
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#using_localstorage_to_store_the_client_id

right now it looks like we aren't using any client identifier at all (i assumed that GA would do this automatically)
https://github.com/Uniswap/interface/blob/7aecf5d3980daa09069bb1847fa0cf57aa1f6bd3/src/components/analytics/index.ts#L6-L11

**Comment by tinaszheng** [comment]
![image](https://user-images.githubusercontent.com/59578595/153129724-afd9bbc7-dc37-4a66-bd01-6463eaa6f627.png)

it looks like clientId is being sent correctly 🤔  is the problem that it is unique each time? [GA](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id) recommends that we persist clientIds through cookies instead of `localStorage`:

> Caution: Unlike cookies, localStorage is bound by the [same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) . If parts of your site are on different subdomains, or if some pages use http and others pages use https, you cannot use localStorage to measure user activity between those pages. For this reason, cookies continues to be the officially recommended way to store the Client ID.

if so we'd just have to remove that option parameter:

`ReactGA.initialize(GOOGLE_ANALYTICS_ID)`

@moodysalem wdyt?

**Comment by willhennessy** [comment]
Reading that excerpt, I think it might be okay to use local storage to track client ID.  The goal is to anonymously count clients using https://app.uniswap.org/*  so the subdomain and https will always be the same. We shouldn't have an issue based on that excerpt
